languageCode: "en-us"
title: "@bwplotka"
theme: "KeepIt"

paginate: 12
enableEmoji: true
enableRobotsTXT: true
publishDir: "public"
canonifyURLs: true
googleAnalytics: "UA-138305173-1"

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

blackfriday:
  hrefTargetBlank: true
  nofollowLinks: true
  noreferrerLinks: true

params:
  since: 2019
  author: "bwplotka"
  avatar: "/images/profile.jpg"
  subtitle: "BartÅ‚omiej PÅ‚otka"
  cdn_url: "" # Base CDN URL
  description: "ğŸ’ªğŸ’»ğŸ"
  keywords: "bwplotka"
  license: 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  social:
    GitHub: "bwplotka"
    Linkedin: "bwplotka"
    Twitter: "bwplotka"
    Email: "bwplotka@gmail.com"

# Used only for Seo schema.
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."